(()=>{"use strict";
const C=document.getElementById("game"),X=C.getContext("2d"),$=id=>document.getElementById(id);
const U={lvl:$("level"),angka:$("angka"),key:$("key"),next:$("next"),energy:$("energy"),power:$("power"),msg:$("message"),over:$("overlay"),start:$("start"),boss:$("bossWrap"),bn:$("bossName"),bb:$("bossBar")};
let W,H,dpr,last=performance.now(),run=false,t=0,msgT=0,lvl=1,A=null;
const img=new Image();img.src=window.MRLEE_SPRITE;
const WORDS=["NOL","SATU","DUA","TIGA","EMPAT","LIMA","ENAM","TUJUH","DELAPAN","SEMBILAN","SEPULUH"];
const S=[["SPORTS CLASS","#8fc9ed","#73964e","cones"],["RUNNING CLUB","#a8d8f0","#5e8844","track"],["AFTER SCHOOL NETBALL","#efb47d","#578557","netball"],["AFTER SCHOOL BASKETBALL","#efa56f","#557b50","basketball"],["FACTION CARNIVAL","#79bce0","#63904e","factions"],["LIGHTNING CARNIVAL","#7bb3d9","#59854c","goals"],["ATHLETICS DAY","#9bd2eb","#708f4d","athletics"],["INDONESIAN WEEK","#e9c581","#6b8d4f","indo"],["SPORTS SHED CHAOS","#70889a","#506a44","shed"],["FINAL · MEGA EVOLUTION","#50576d","#425b3d","final"]];
const K={f:0,b:0,l:0,r:0,run:0,jump:0,throw:0};
let p,items,enemies,balls,fruit,powers,holes,keyObj,exit,bq,boss,audio;
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,1.5);C.width=W*dpr;C.height=H*dpr;X.setTransform(dpr,0,0,dpr,0,0)}addEventListener("resize",resize);resize();
const rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
function tone(f=440,d=.07,type="square"){try{audio??=new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type=type;g.gain.value=.04;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch(e){}}
function say(s,ms=1200){U.msg.textContent=s;U.msg.classList.add("show");msgT=t+ms/1000}
function enemy(x,z,sc=.55,hp=3){return{x,z,sc,hp,max:hp,dead:0,phase:rnd(0,9),shoot:rnd(1.4,3.2),dance:0}}
function init(n){lvl=n;p={x:0,z:6,y:0,vy:0,yaw:0,e:5,next:0,key:0,safe:6,inv:0,resp:0,respect:0,ach:0,rary:0,rescue:0,cd:0};items=[];enemies=[];balls=[];fruit=[];powers=[];holes=[];keyObj={x:0,z:194,on:0};exit={x:0,z:224};bq=[];boss=null;for(let i=0;i<11;i++)items.push({x:[-7,0,7][i%3],z:23+i*14,w:WORDS[i],n:i,on:1});if(n>=3)holes.push([73,83]);if(n>=6)holes.push([125,135]);if(n>=8)holes.push([164,174]);for(let i=0;i<Math.min(2+n,8);i++)enemies.push(enemy((i%2?1:-1)*rnd(5,10),45+i*(130/Math.min(2+n,8)),.5+n*.012,3));powers=[{k:"resp",x:-9,z:64,on:1},{k:"respect",x:9,z:110,on:1},{k:"ach",x:-8,z:150,on:1},{k:"rary",x:8,z:181,on:1}];if(n===5)bq=[["MEDIUM MR LEE",50,.86]];if(n===10)bq=[["SMALL MR LEE",10,.5],["MEDIUM MR LEE",50,.82],["LARGE MR LEE",100,1.08],["MEGA EVOLUTION MR LEE",200,1.4]];nextBoss();hud();say("LEVEL "+n+" · "+S[n-1][0],1500)}
function nextBoss(){if(!bq.length){boss=null;U.boss.style.display="none";return}let q=bq.shift();boss={name:q[0],hp:q[1],max:q[1],sc:q[2],x:0,z:188,dead:0,phase:0,shoot:1.2};U.boss.style.display="block";bossHud()}
function bossHud(){if(!boss){U.boss.style.display="none";return}U.bn.textContent=boss.name;U.bb.style.width=Math.max(0,boss.hp/boss.max*100)+"%"}
function hud(){U.lvl.textContent="LEVEL "+lvl+" · "+S[lvl-1][0];U.angka.textContent="ANGKA "+p.next+" / 11";U.key.textContent="KUNCI "+(p.key?1:0)+" / 1";U.next.textContent=p.next<11?"NEXT "+WORDS[p.next]+" ("+p.next+")":"NUMBERS COMPLETE";U.energy.textContent="ENERGI "+"♥ ".repeat(p.e).trim();let a=[];if(p.resp>t)a.push("◆ RESPONSIBILITY");if(p.respect>t)a.push("🤝 RESPECT");if(p.ach>t)a.push("★ ACHIEVER");if(p.rary>t)a.push("🦁 RARY · MAX AURA");U.power.textContent=a.length?a.join(" · "):"◆ RESPONSIBILITY · 🤝 RESPECT · ★ ACHIEVER"}
function hole(){return holes.some(h=>p.z>h[0]&&p.z<h[1]&&Math.abs(p.x)<14)}
function hit(){if(p.inv>t||p.ach>t||p.rary>t)return;if(p.rescue){p.rescue=0;p.e=5;p.inv=t+2;say("RARY RESCUE! MAX AURA SAVED YOU!",1700);tone(620,.2,"triangle");return}p.e--;p.inv=t+1.1;tone(120,.15,"sawtooth");if(p.e<=0){p.e=5;p.x=0;p.z=Math.max(6,p.safe-6);p.y=0;p.vy=0;say("MR LEE GOT YOU — TRY AGAIN!",1500)}hud()}
function pow(o){o.on=0;if(o.k==="resp"){p.resp=t+15;say("RESPONSIBILITY! FIVE RICOCHETING DODGEBALLS!",1800)}if(o.k==="respect"){p.respect=t+12;say("RESPECT! FRUIT → CONFETTI · DANCE PARTY!",1800)}if(o.k==="ach"){p.ach=t+15;p.inv=t+15;say("ACHIEVER! SPEED + INVINCIBILITY + SMASHING AURA!",1900)}if(o.k==="rary"){p.rary=p.resp=p.respect=p.ach=p.inv=t+18;p.rescue=1;p.e=5;say("RARY RETURNS! MAX AURA!",1900);tone(760,.24,"triangle")}hud()}
function shoot(){if(p.cd>t)return;p.cd=t+.28;let c=(p.resp>t||p.rary>t)?5:1;for(let i=0;i<c;i++){let off=(i-(c-1)/2)*.1;balls.push({x:p.x,z:p.z+1,a:p.yaw+off,v:34,life:2.7,b:c>1?3:1,ph:rnd(0,6)})}tone(260,.05)}
function die(e,s="MINI MR LEE BONKED!"){if(e.dead)return;e.dead=1;tone(520,.07);say(s,850)}
function bossDead(){let name=boss.name;boss.dead=1;tone(820,.2,"sawtooth");say(name+" DEFEATED!",1300);setTimeout(()=>{boss=null;nextBoss()},500)}
function upd(dt){if(!run)return;t+=dt;if(t>msgT)U.msg.classList.remove("show");let fast=(K.run||p.ach>t||p.rary>t)?10.5:6.5;p.yaw+=(K.r-K.l)*2.05*dt;let m=K.f-K.b;p.x+=Math.sin(p.yaw)*fast*m*dt;p.z+=Math.cos(p.yaw)*fast*m*dt;p.x=Math.max(-14,Math.min(14,p.x));p.z=Math.max(3,Math.min(228,p.z));if(K.jump&&p.y<=.01){p.vy=9.2;tone(330,.05)}p.vy-=19*dt;p.y+=p.vy*dt;if(p.y<0){p.y=0;p.vy=0}if(hole()&&p.y<.75){hit();p.x=0;p.z=Math.max(6,p.safe-5);say("DOWN THE HOLE! 😂",1000)}else if(p.y<.1)p.safe=p.z;if(p.y>.45){for(let e of enemies)if(!e.dead&&dist(p,e)<2.1)die(e,"BOING! MINI MR LEE STOMPED!");if(boss&&!boss.dead&&dist(p,boss)<2.3+boss.sc){boss.hp-=8;p.vy=8;bossHud();if(boss.hp<=0)bossDead()}}for(let o of items)if(o.on&&dist(p,o)<2.2){if(o.n===p.next){o.on=0;p.next++;tone(560+o.n*24,.07);say(o.w+" ("+o.n+")!",700);if(p.next===11){keyObj.on=1;say("SEMUA ANGKA! FIND THE KEY!",1300)}hud()}else{say("NEXT IS "+WORDS[p.next]+"!",800);tone(110,.1,"sawtooth")}}if(keyObj.on&&!p.key&&dist(p,keyObj)<2.2){p.key=1;keyObj.on=0;say("KUNCI! GET TO THE SPORTS SHED!",1300);tone(880,.14,"triangle");hud()}for(let o of powers)if(o.on&&dist(p,o)<2.2)pow(o);for(let e of enemies)if(!e.dead){e.phase+=dt;e.dance=(p.respect>t||p.rary>t);e.shoot-=dt;if(e.shoot<=0&&dist(p,e)<35){e.shoot=rnd(2.2,4);let a=Math.atan2(p.x-e.x,p.z-e.z);fruit.push({x:e.x,z:e.z,a,v:10,life:4,ico:["🥦","🥕","🍎","🍌","🫛"][Math.floor(Math.random()*5)]})}}if(boss&&!boss.dead){boss.phase+=dt;boss.shoot-=dt;if(boss.shoot<=0&&dist(p,boss)<45){boss.shoot=Math.max(.8,1.7-boss.sc*.4);let a=Math.atan2(p.x-boss.x,p.z-boss.z);fruit.push({x:boss.x,z:boss.z,a,v:12+boss.sc*2,life:4,ico:"🍎"})}}for(let b of balls){b.life-=dt;b.x+=Math.sin(b.a)*b.v*dt;b.z+=Math.cos(b.a)*b.v*dt;b.ph+=dt*13;if(Math.abs(b.x)>14&&b.b>0){b.a=-b.a;b.b--;b.x=Math.max(-14,Math.min(14,b.x))}for(let e of enemies)if(!e.dead&&Math.hypot(e.x-b.x,e.z-b.z)<1.7){e.hp-=5;b.life=0;if(e.hp<=0)die(e)}if(boss&&!boss.dead&&Math.hypot(boss.x-b.x,boss.z-b.z)<2+boss.sc){boss.hp-=5;b.life=0;bossHud();if(boss.hp<=0)bossDead()}}balls=balls.filter(b=>b.life>0&&b.z>-5&&b.z<245);for(let f of fruit){f.life-=dt;f.x+=Math.sin(f.a)*f.v*dt;f.z+=Math.cos(f.a)*f.v*dt;if((p.respect>t||p.rary>t)&&dist(p,f)<7){f.conf=1;f.life=Math.min(f.life,.25)}else if(dist(p,f)<1.2&&p.y<1.7){f.life=0;hit()}}fruit=fruit.filter(f=>f.life>0);if(p.ach>t||p.rary>t)for(let e of enemies)if(!e.dead&&dist(p,e)<2.3)die(e,"AURA SMASH!");if(p.key&&dist(p,exit)<2.8&&!boss&&!bq.length){if(lvl<10)init(lvl+1);else{run=false;U.over.style.display="grid";U.start.textContent="PLAY AGAIN";say("YOU FOUND MR LEE'S KEYS!",2200)}}}
function cam(){return{x:p.x-Math.sin(p.yaw)*5.4,z:p.z-Math.cos(p.yaw)*5.4,y:3.4+p.y*.15,a:p.yaw}}
function pr(x,z,y=0){let c=cam(),dx=x-c.x,dz=z-c.z,co=Math.cos(c.a),si=Math.sin(c.a),sx=dx*co-dz*si,d=dx*si+dz*co;if(d<.35)return null;let f=Math.min(W,H)*.86,s=f/d;return{x:W/2+sx*s,y:H*.42+(c.y-y)*s,s,d}}
function bg(){let s=S[lvl-1],h=H*.42;X.fillStyle=s[1];X.fillRect(0,0,W,h);X.fillStyle=s[2];X.fillRect(0,h,W,H-h);X.strokeStyle="#ffffff22";for(let i=-7;i<=7;i++){X.beginPath();X.moveTo(W/2,h);X.lineTo(W/2+i*W*.12,H);X.stroke()}let c=cam();for(let z=Math.ceil(c.z/10)*10;z<c.z+170;z+=10){let a=pr(-15,z),b=pr(15,z);if(a&&b){X.globalAlpha=Math.max(.04,.22-a.d/900);X.beginPath();X.moveTo(a.x,a.y);X.lineTo(b.x,b.y);X.stroke()}}X.globalAlpha=1;box(-22,75,18,5,"#d9d0ba","MARANGAROO PRIMARY");box(21,120,12,5,"#d1c9b7","SPORTS BLOCK");props();for(let h0 of holes)pit(h0)}
function box(x,z,w,h,c,txt){let q=pr(x,z);if(!q||q.d>180)return;let ww=w*q.s,hh=h*q.s;X.fillStyle=c;X.fillRect(q.x-ww/2,q.y-hh,ww,hh);X.fillStyle="#3f6555";X.fillRect(q.x-ww/2,q.y-hh,ww,.7*q.s);if(q.s>5){X.fillStyle="#273a38";X.font=Math.max(8,Math.min(16,q.s*.5))+"px system-ui";X.textAlign="center";X.fillText(txt,q.x,q.y-hh*.45)}}
function pit(h){let a=pr(-14,h[0]),b=pr(14,h[0]),c=pr(14,h[1]),d=pr(-14,h[1]);if(!a||!b||!c||!d)return;X.fillStyle="#111923";X.beginPath();X.moveTo(a.x,a.y);X.lineTo(b.x,b.y);X.lineTo(c.x,c.y);X.lineTo(d.x,d.y);X.closePath();X.fill()}
function props(){let k=S[lvl-1][3],a=[];if(["cones","track","athletics"].includes(k))for(let i=0;i<10;i++)a.push(["cone",(i%2?1:-1)*10,30+i*15]);if(k==="netball")a.push(["hoop",-9,60],["hoop",9,145]);if(k==="basketball")a.push(["basket",-9,58],["basket",9,145]);if(k==="factions")a.push(["flag",-8,70,"#e9444b"],["flag",0,70,"#f1d23f"],["flag",8,70,"#34a15b"]);if(k==="indo")["SELAMAT!","BAGUS!","AYO!","HEBAT!"].forEach((q,i)=>a.push(["sign",i%2?-10:10,55+i*30,q]));for(let z=45;z<210;z+=55)a.push(["sulo",z%110?12:-12,z]);a.forEach(drawProp)}
function drawProp(a){let [k,x,z,e]=a,q=pr(x,z);if(!q||q.d>170)return;let s=q.s;if(k==="sulo"){X.fillStyle="#123e2a";X.fillRect(q.x-.8*s,q.y-2.3*s,1.6*s,2.3*s);X.fillStyle="#0a2c1c";X.fillRect(q.x-.92*s,q.y-2.5*s,1.84*s,.25*s);X.fillStyle="#fff";X.font=Math.max(7,.45*s)+"px system-ui";X.textAlign="center";X.fillText("SULO",q.x,q.y-1.05*s)}if(k==="cone"){X.fillStyle="#ff7b35";X.beginPath();X.moveTo(q.x,q.y-1.2*s);X.lineTo(q.x-.55*s,q.y);X.lineTo(q.x+.55*s,q.y);X.fill()}if(k==="hoop"||k==="basket"){X.strokeStyle="#eef2f3";X.lineWidth=Math.max(2,.07*s);X.beginPath();X.moveTo(q.x,q.y);X.lineTo(q.x,q.y-4.2*s);X.stroke();X.strokeStyle=k==="basket"?"#f05b3d":"#fff";X.beginPath();X.ellipse(q.x,q.y-4.1*s,.55*s,.18*s,0,0,7);X.stroke();if(k==="basket"){X.strokeStyle="#fff";X.strokeRect(q.x-1.1*s,q.y-5.1*s,2.2*s,1.25*s)}}if(k==="flag"){X.strokeStyle="#eee";X.beginPath();X.moveTo(q.x,q.y);X.lineTo(q.x,q.y-4*s);X.stroke();X.fillStyle=e;X.fillRect(q.x,q.y-4*s,2.2*s,1.1*s)}if(k==="sign"){X.fillStyle="#b82929";X.fillRect(q.x-2.8*s,q.y-3.6*s,5.6*s,1.3*s);X.fillStyle="#fff";X.font=Math.max(8,.62*s)+"px system-ui";X.textAlign="center";X.fillText(e,q.x,q.y-2.7*s)}}
function sprite(x,z,sc,fr,label){let q=pr(x,z);if(!q||q.d>165)return;let sw=40,sh=91,dh=Math.min(H*.62,sh*q.s*.035*sc),dw=dh*(sw/sh);X.drawImage(img,fr*40,0,40,91,q.x-dw/2,q.y-dh,dw,dh);if(label&&q.s>4){X.font="900 "+Math.max(8,Math.min(17,q.s*.5))+"px system-ui";X.textAlign="center";X.strokeStyle="#000";X.lineWidth=4;X.strokeText(label,q.x,q.y-dh-5);X.fillStyle="#fff";X.fillText(label,q.x,q.y-dh-5)}}
function orb(o){if(!o.on)return;let q=pr(o.x,o.z,1);if(!q)return;let r=Math.max(5,Math.min(22,q.s*.5));X.shadowColor="#ffd84d";X.shadowBlur=r;X.fillStyle="#f7dc52";X.beginPath();X.arc(q.x,q.y,r,0,7);X.fill();X.shadowBlur=0;X.fillStyle="#173426";X.font="1000 "+Math.max(8,r*.72)+"px system-ui";X.textAlign="center";X.textBaseline="middle";X.fillText(o.n,q.x,q.y);X.textBaseline="alphabetic";X.fillStyle="#fff";X.font="900 "+Math.max(8,r*.6)+"px system-ui";X.strokeStyle="#000";X.lineWidth=3;X.strokeText(o.w,q.x,q.y-r-5);X.fillText(o.w,q.x,q.y-r-5)}
function power(o){if(!o.on)return;let q=pr(o.x,o.z,1);if(!q)return;let ic={resp:"◆",respect:"🤝",ach:"★",rary:"🦁"},nm={resp:"RESPONSIBILITY",respect:"RESPECT",ach:"ACHIEVER",rary:"RARY MAX AURA"};X.textAlign="center";X.font=Math.max(14,q.s*1.15)+"px system-ui";X.fillText(ic[o.k],q.x,q.y);X.font="900 "+Math.max(8,q.s*.4)+"px system-ui";X.strokeStyle="#000";X.lineWidth=3;X.strokeText(nm[o.k],q.x,q.y-20);X.fillStyle="#fff";X.fillText(nm[o.k],q.x,q.y-20)}
function keyExit(){if(keyObj.on){let q=pr(keyObj.x,keyObj.z,1);if(q){X.font=Math.max(18,q.s*1.1)+"px system-ui";X.textAlign="center";X.fillText("🔑",q.x,q.y)}}let q=pr(exit.x,exit.z);if(q){let s=q.s;X.fillStyle="#284a34";X.fillRect(q.x-3.3*s,q.y-4.6*s,6.6*s,4.6*s);X.fillStyle="#123522";X.fillRect(q.x-1.6*s,q.y-3.6*s,3.2*s,3.6*s);X.fillStyle="#fff";X.font=Math.max(8,.48*s)+"px system-ui";X.textAlign="center";X.fillText("SPORTS SHED",q.x,q.y-4*s)}}
function render(){bg();let c=cam(),a=[];for(let o of items)if(o.on)a.push([Math.hypot(o.x-c.x,o.z-c.z),()=>orb(o)]);for(let o of powers)if(o.on)a.push([Math.hypot(o.x-c.x,o.z-c.z),()=>power(o)]);for(let e of enemies)if(!e.dead)a.push([Math.hypot(e.x-c.x,e.z-c.z),()=>sprite(e.x,e.z,e.sc,e.dance?2:(Math.sin(e.phase*2)>0?0:1),"MINI MR LEE")]);if(boss&&!boss.dead)a.push([Math.hypot(boss.x-c.x,boss.z-c.z),()=>sprite(boss.x,boss.z,boss.sc,2,boss.name)]);a.sort((x,y)=>y[0]-x[0]).forEach(q=>q[1]());keyExit();for(let f of fruit){let q=pr(f.x,f.z,1.4);if(q){X.font=Math.max(10,Math.min(30,q.s*.7))+"px system-ui";X.textAlign="center";X.fillText(f.conf?"🎉":f.ico,q.x,q.y)}}for(let b of balls){let q=pr(b.x,b.z,.65+Math.abs(Math.sin(b.ph))*.7);if(q){let r=Math.max(3,Math.min(14,q.s*.28));X.fillStyle="#ff66b2";X.strokeStyle="#fff";X.lineWidth=2;X.beginPath();X.arc(q.x,q.y,r,0,7);X.fill();X.stroke()}}let ph=Math.min(H*.48,300),pw=ph*.438,fr=K.throw?1:(p.y>0?3:0);if(p.ach>t||p.rary>t){X.shadowColor="#ffd84d";X.shadowBlur=25}X.drawImage(img,fr*40,0,40,91,W/2-pw/2,H-ph-8,pw,ph);X.shadowBlur=0;if(p.rary>t){X.font="1000 18px system-ui";X.textAlign="center";X.strokeStyle="#000";X.lineWidth=4;X.strokeText("🦁 MAX AURA",W/2,H-18);X.fillStyle="#ffd84d";X.fillText("🦁 MAX AURA",W/2,H-18)}}
function loop(n){let dt=Math.min(.033,(n-last)/1000||0);last=n;upd(dt);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function set(k,v){K[k]=v?1:0}
addEventListener("keydown",e=>{if(["KeyW","ArrowUp"].includes(e.code))set("f",1);if(["KeyS","ArrowDown"].includes(e.code))set("b",1);if(["KeyA","ArrowLeft"].includes(e.code))set("l",1);if(["KeyD","ArrowRight"].includes(e.code))set("r",1);if(e.code.startsWith("Shift"))set("run",1);if(e.code==="KeyJ")set("jump",1);if(e.code==="Space"){e.preventDefault();set("throw",1);shoot()}});
addEventListener("keyup",e=>{if(["KeyW","ArrowUp"].includes(e.code))set("f",0);if(["KeyS","ArrowDown"].includes(e.code))set("b",0);if(["KeyA","ArrowLeft"].includes(e.code))set("l",0);if(["KeyD","ArrowRight"].includes(e.code))set("r",0);if(e.code.startsWith("Shift"))set("run",0);if(e.code==="KeyJ")set("jump",0);if(e.code==="Space")set("throw",0)});
document.querySelectorAll(".btn").forEach(b=>{let k=b.dataset.k,d=e=>{e.preventDefault();b.classList.add("on");set(k,1);if(k==="throw")shoot()},u=e=>{e.preventDefault();b.classList.remove("on");set(k,0)};b.addEventListener("pointerdown",d,{passive:false});b.addEventListener("pointerup",u,{passive:false});b.addEventListener("pointercancel",u,{passive:false})});
U.start.onclick=()=>{try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume()}catch(e){}U.over.style.display="none";run=true;init(1);last=performance.now()};
init(1);
})();