import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=s=>document.querySelector(s);
const ui={overlay:$('#overlay'),start:$('#startBtn'),msg:$('#message'),level:$('#levelPill'),angka:$('#angkaPill'),key:$('#keyPill'),next:$('#nextPill'),energy:$('#energyPill'),power:$('#powerPill'),bossWrap:$('#bossBarWrap'),bossName:$('#bossName'),bossBar:$('#bossBar')};
const scene=new THREE.Scene();
scene.background=new THREE.Color(0x87bde0);
scene.fog=new THREE.Fog(0x87bde0,65,165);
const camera=new THREE.PerspectiveCamera(66,innerWidth/innerHeight,.1,500);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; document.body.prepend(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xd9efff,0x6b7d58,2.1); scene.add(hemi);
const sun=new THREE.DirectionalLight(0xfff1ce,3.2); sun.position.set(-35,55,24); sun.castShadow=true; sun.shadow.mapSize.set(1024,1024); sun.shadow.camera.left=-75;sun.shadow.camera.right=75;sun.shadow.camera.top=75;sun.shadow.camera.bottom=-75; scene.add(sun);

const STAGES=[
{name:'SPORTS CLASS',sky:0x8fc9ed,ground:0x799d57,accent:0xf4d35e,prop:'cones'},
{name:'RUNNING CLUB',sky:0xa8d8f0,ground:0x628b43,accent:0xe85d4a,prop:'track'},
{name:'AFTER SCHOOL NETBALL',sky:0xf1b77d,ground:0x5c8f57,accent:0xff8ab9,prop:'netball'},
{name:'AFTER SCHOOL BASKETBALL',sky:0xf0aa71,ground:0x527d52,accent:0xf3a03c,prop:'basketball'},
{name:'FACTION CARNIVAL',sky:0x73b7dd,ground:0x64934f,accent:0xe84855,prop:'factions'},
{name:'LIGHTNING CARNIVAL',sky:0x7ab2d8,ground:0x5a864c,accent:0xffd84d,prop:'goals'},
{name:'ATHLETICS DAY',sky:0x9ad4ef,ground:0x6f934b,accent:0xf59e42,prop:'athletics'},
{name:'INDONESIAN WEEK',sky:0xeac781,ground:0x6b8e4d,accent:0xe74c3c,prop:'indo'},
{name:'SPORTS SHED CHAOS',sky:0x71889c,ground:0x516c45,accent:0x3d8b5a,prop:'shed'},
{name:'FINAL · MEGA EVOLUTION',sky:0x4c5269,ground:0x435d3b,accent:0xff4f76,prop:'final'}
];
const WORDS=[['NOL',0],['SATU',1],['DUA',2],['TIGA',3],['EMPAT',4],['LIMA',5],['ENAM',6],['TUJUH',7],['DELAPAN',8],['SEMBILAN',9],['SEPULUH',10]];
const LEVEL_LEN=230, CORRIDOR=34;
let level=1, running=false, gameTime=0, last=performance.now(), messageTimer=0, throwCool=0, enemyThrowClock=0;
let world=new THREE.Group(); scene.add(world);
let pickups=[],enemies=[],balls=[],fruit=[],particles=[],powerups=[],holes=[],exitGate=null,keyObj=null,boss=null,bossQueue=[],bossIndex=-1;
const keys={forward:false,back:false,left:false,right:false,run:false,jump:false,throw:false};
const state={angka:0,hasKey:false,energy:5,maxEnergy:5,respUntil:0,respectUntil:0,achieverUntil:0,raryUntil:0,rescue:0,invulnUntil:0,lastSafe:new THREE.Vector3(0,1.2,6)};

function mat(c,rough=.75,metal=0){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}
function box(w,h,d,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.castShadow=m.receiveShadow=true;return m}
function cyl(r,h,c,seg=16){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),mat(c));m.castShadow=m.receiveShadow=true;return m}
function sphere(r,c,seg=16){const m=new THREE.Mesh(new THREE.SphereGeometry(r,seg,Math.max(8,seg/2)),mat(c));m.castShadow=m.receiveShadow=true;return m}
function canvasTexture(text,bg='#153e28',fg='#fff',w=256,h=96,size=54){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,w,h);x.fillStyle=fg;x.font=`900 ${size}px system-ui`;x.textAlign='center';x.textBaseline='middle';x.fillText(text,w/2,h/2);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function textSprite(text,fg='#fff',bg='rgba(0,0,0,.65)',scale=5){const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,512,160);x.fillStyle=fg;x.font='900 64px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,80);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false}));sp.scale.set(scale,scale*.31,1);return sp}

function makePlayer(){const g=new THREE.Group();
 const torso=box(1.35,1.85,.72,0x163d6b);torso.position.y=2.35;g.add(torso);
 const shorts=box(1.42,.7,.76,0x182332);shorts.position.y=1.15;g.add(shorts);
 const head=sphere(.58,0x8b542f,18);head.position.y=3.65;g.add(head);
 const hair=new THREE.Mesh(new THREE.SphereGeometry(.60,16,8,0,Math.PI*2,0,Math.PI*.47),mat(0x17120f));hair.position.set(0,3.83,0);g.add(hair);
 for(const sx of [-1,1]){const a=cyl(.18,1.55,0x6f3e24,12);a.rotation.z=sx*.15;a.position.set(sx*.83,2.35,0);g.add(a)}
 for(const sx of [-1,1]){const leg=cyl(.22,1.35,0x7a5231,12);leg.position.set(sx*.35,.23,0);g.add(leg);const shoe=box(.52,.24,.85,0x131722);shoe.position.set(sx*.35,-.47,.18);g.add(shoe)}
 const aura=new THREE.Mesh(new THREE.TorusGeometry(1.35,.09,8,36),new THREE.MeshBasicMaterial({color:0xffdd55,transparent:true,opacity:0}));aura.rotation.x=Math.PI/2;aura.position.y=1.25;g.add(aura);g.userData.aura=aura;
 g.position.set(0,1,8);g.rotation.y=Math.PI;return g}
const player=makePlayer();scene.add(player);let velY=0,onGround=false,playerYaw=Math.PI;

function makeMiniMrLee(scale=1){const g=new THREE.Group();
 const skin=0x3f261d; const shirt=0x162938;
 const body=box(1.25*scale,1.6*scale,.72*scale,shirt);body.position.y=1.9*scale;g.add(body);
 const head=sphere(.56*scale,skin,14);head.position.y=3.05*scale;g.add(head);
 const hair=sphere(.58*scale,0x0e0d0c,12);hair.scale.y=.38;hair.position.y=3.35*scale;g.add(hair);
 for(const sx of [-1,1]){const upper=cyl(.23*scale,1.25*scale,skin,10);upper.position.set(sx*.88*scale,2.1*scale,0);upper.rotation.z=sx*.5;g.add(upper);const bicep=sphere(.32*scale,skin,10);bicep.position.set(sx*1.15*scale,2.55*scale,0);g.add(bicep)}
 for(const sx of [-1,1]){const leg=cyl(.22*scale,1.25*scale,0x20242a,10);leg.position.set(sx*.32*scale,.65*scale,0);g.add(leg)}
 g.userData={hp:3,maxHp:3,dead:false,danceSeed:Math.random()*10,scale,kind:'enemy'};return g}
function makeBoss(name,hp,scale){const g=makeMiniMrLee(scale);g.userData.kind='boss';g.userData.hp=hp;g.userData.maxHp=hp;g.userData.name=name; const label=textSprite(name.toUpperCase(),'#fff','rgba(75,0,0,.72)',7*scale);label.position.y=4.45*scale;g.add(label);return g}

function addSchoolBackdrop(){
 const b=box(30,8,10,0xd8d2bf);b.position.set(-27,4,-74);world.add(b); const roof=box(31,1,11,0x365c55);roof.position.set(-27,8.5,-74);world.add(roof);
 for(let i=0;i<5;i++){const win=box(3,2,.12,0x7eb5c5);win.position.set(-37+i*5,4,-68.95);world.add(win)}
 for(let i=0;i<10;i++){const trunk=cyl(.35,5,0x715236,8);trunk.position.set(i%2?27:-27,2.5,-10-i*18);world.add(trunk);const crown=sphere(2.5,0x577d45,10);crown.scale.set(1,1.5,.8);crown.position.set(i%2?27:-27,6,-10-i*18);world.add(crown)}
}
function addSulo(x,z,rot=0){const g=new THREE.Group();const bin=box(2.1,3.2,2.0,0x123e2a);bin.position.y=1.6;g.add(bin);const lid=box(2.35,.32,2.18,0x0a2c1c);lid.position.set(0,3.28,-.05);lid.rotation.x=-.12;g.add(lid);for(const sx of [-1,1]){const w=cyl(.24,.22,0x151515,10);w.rotation.z=Math.PI/2;w.position.set(sx*.72,.22,.88);g.add(w)}const sign=new THREE.Mesh(new THREE.PlaneGeometry(1.6,.6),new THREE.MeshBasicMaterial({map:canvasTexture('SULO','#123e2a','#ffffff',256,96,50)}));sign.position.set(0,2.1,1.015);g.add(sign);g.position.set(x,0,z);g.rotation.y=rot;world.add(g)}
function hoop(x,z,type='netball'){const g=new THREE.Group();const pole=cyl(.12,4.2,0xd9dde2,12);pole.position.y=2.1;g.add(pole);const ring=new THREE.Mesh(new THREE.TorusGeometry(.52,.06,8,24),mat(type==='netball'?0xffffff:0xf05b3d));ring.rotation.x=Math.PI/2;ring.position.set(0,4.1,.5);g.add(ring);if(type==='basketball'){const board=box(2.2,1.25,.12,0xf4f4f0);board.position.set(0,4.65,.18);g.add(board)}g.position.set(x,0,z);world.add(g)}
function addProps(kind){
 if(kind==='netball'){hoop(-9,-35);hoop(9,-120)}
 if(kind==='basketball'){hoop(-9,-35,'basketball');hoop(9,-120,'basketball')}
 if(kind==='cones'||kind==='athletics'||kind==='track'){for(let i=0;i<12;i++){const c=new THREE.Mesh(new THREE.ConeGeometry(.35,.9,10),mat(i%2?0xff7a34:0xf5d550));c.position.set((i%2?1:-1)*10,.45,-8-i*14);world.add(c)}}
 if(kind==='factions'){for(const [x,c] of [[-9,0xe63d45],[0,0xf3d447],[9,0x2ca55f]]){const flag=box(.08,4,.08,0xe7e7e7);flag.position.set(x,2,-55);world.add(flag);const f=box(2.6,1.4,.05,c);f.position.set(x,3.7,-55);world.add(f)}}
 if(kind==='goals'){for(const x of [-8,8]){const p1=cyl(.12,4.6,0xffffff,10);p1.position.set(x-1,2.3,-85);world.add(p1);const p2=p1.clone();p2.position.x=x+1;world.add(p2)}}
 if(kind==='indo'){for(let i=0;i<5;i++){const s=textSprite(['SELAMAT!','BAGUS!','AYO!','TERIMA KASIH!','HEBAT!'][i],'#fff','rgba(180,35,35,.75)',6);s.position.set(i%2?11:-11,4,-30-i*30);world.add(s)}}
 if(kind==='shed'||kind==='final'){const shed=box(18,7,10,0x43614c);shed.position.set(0,3.5,-188);world.add(shed);const door=box(6,5,.15,0x183c28);door.position.set(0,2.5,-182.95);world.add(door)}
 for(let z=-25;z>-205;z-=55){addSulo(Math.random()<.5?-14:14,z,Math.random()<.5?0:Math.PI)}
}
function groundTile(z1,z2){const len=Math.abs(z2-z1);const g=box(CORRIDOR,.45,len,STAGES[level-1].ground);g.position.set(0,-.25,(z1+z2)/2);g.receiveShadow=true;world.add(g)}
function buildGround(){holes=[]; const holeStarts=[]; if(level>=3)holeStarts.push(-52);if(level>=6)holeStarts.push(-112);if(level>=8)holeStarts.push(-162);let cursor=10;for(const h of holeStarts){groundTile(cursor,h+5);holes.push({z1:h-5,z2:h+5});cursor=h-5}groundTile(cursor,-LEVEL_LEN)}
function createPickup(word,index,x,z){const g=new THREE.Group();const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.72,1),new THREE.MeshStandardMaterial({color:0xf4d84d,emissive:0x594600,emissiveIntensity:.5,roughness:.35}));g.add(orb);const label=textSprite(`${word} (${index})`,'#1a2a18','rgba(255,245,155,.96)',3.7);label.position.y=1.45;g.add(label);g.position.set(x,1.25,z);g.userData={index,word,collected:false,baseY:1.25,phase:Math.random()*6};world.add(g);pickups.push(g)}
function spawnPickups(){pickups=[];for(let i=0;i<WORDS.length;i++){const z=-8-i*15.7-(i>6?5:0);const x=(i%3-1)*7;createPickup(WORDS[i][0],i,x,z)}}
function spawnEnemies(){enemies=[];const count=Math.min(2+level,9);for(let i=0;i<count;i++){const e=makeMiniMrLee(.78+level*.015);e.position.set((i%2?1:-1)*(5+Math.random()*7),0,-22-i*(155/count));e.userData.homeX=e.position.x;e.userData.homeZ=e.position.z;e.userData.phase=Math.random()*20;world.add(e);enemies.push(e)}}
function createKey(){keyObj=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.7,.18,10,24),mat(0xffd53a,.25,.45));ring.rotation.y=Math.PI/2;keyObj.add(ring);const shaft=box(1.5,.25,.25,0xffd53a);shaft.position.x=1.15;keyObj.add(shaft);const tooth=box(.35,.6,.25,0xffd53a);tooth.position.set(1.65,-.25,0);keyObj.add(tooth);keyObj.position.set(0,2,-181);keyObj.visible=false;world.add(keyObj)}
function createExit(){exitGate=new THREE.Group();for(const x of [-4,4]){const p=box(.7,7,.7,0xd7d8d7);p.position.set(x,3.5,-211);exitGate.add(p)}const top=box(8.7,.7,.7,0xd7d8d7);top.position.set(0,6.7,-211);exitGate.add(top);const sign=textSprite('SPORTS SHED →','#fff','rgba(14,65,38,.92)',7);sign.position.set(0,8,-211);exitGate.add(sign);world.add(exitGate)}
function clearWorld(){scene.remove(world);world=new THREE.Group();scene.add(world);pickups=[];enemies=[];balls=[];fruit=[];particles=[];powerups=[];holes=[];boss=null;bossQueue=[];bossIndex=-1;ui.bossWrap.style.display='none'}
function buildLevel(){clearWorld();state.angka=0;state.hasKey=false;state.energy=state.maxEnergy;state.respUntil=state.respectUntil=state.achieverUntil=state.raryUntil=0;state.rescue=0;ui.key.textContent='KUNCI 0 / 1';scene.background=new THREE.Color(STAGES[level-1].sky);scene.fog.color.copy(scene.background);buildGround();addSchoolBackdrop();addProps(STAGES[level-1].prop);spawnPickups();spawnEnemies();createKey();createExit();player.position.set(0,1.1,8);playerYaw=Math.PI;player.rotation.y=playerYaw;velY=0;state.lastSafe.copy(player.position);updateHUD();say(`LEVEL ${level} · ${STAGES[level-1].name}`,1.7)}

function updateHUD(){ui.level.textContent=`LEVEL ${level} · ${STAGES[level-1].name}`;ui.angka.textContent=`ANGKA ${state.angka} / 11`;ui.key.textContent=`KUNCI ${state.hasKey?1:0} / 1`;ui.next.textContent=state.angka<11?`NEXT ${WORDS[state.angka][0]} (${state.angka})`:'NEXT KUNCI';ui.energy.textContent=`ENERGI ${'♥ '.repeat(state.energy)}${'♡ '.repeat(Math.max(0,state.maxEnergy-state.energy))}`.trim();const active=[];if(gameTime<state.respUntil)active.push('◆ RESPONSIBILITY ×5');if(gameTime<state.respectUntil)active.push('🤝 RESPECT DANCE');if(gameTime<state.achieverUntil)active.push('★ ACHIEVER AURA');if(gameTime<state.raryUntil)active.push('🦁 RARY MAX AURA');ui.power.textContent=active.length?active.join(' · '):'◆ RESPONSIBILITY · 🤝 RESPECT · ★ ACHIEVER'}
function say(html,secs=1.4){ui.msg.innerHTML=html;ui.msg.classList.add('show');messageTimer=gameTime+secs}
let audioCtx=null;function audio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(freq=440,dur=.12,type='sine',vol=.08){try{const a=audio(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch{}}
function collisionXZ(a,b,rad=1.45){const dx=a.position.x-b.position.x,dz=a.position.z-b.position.z;return dx*dx+dz*dz<rad*rad}
function inHole(pos){return holes.some(h=>pos.z<=h.z1&&pos.z>=h.z2&&Math.abs(pos.x)<CORRIDOR/2)}
function damagePlayer(n=1,knock=null){if(gameTime<state.invulnUntil||gameTime<state.achieverUntil||gameTime<state.raryUntil)return;if(state.energy<=0)return;state.energy=Math.max(0,state.energy-n);state.invulnUntil=gameTime+1.2;tone(150,.18,'sawtooth',.09);if(knock){player.position.x+=knock.x;player.position.z+=knock.z}updateHUD();if(state.energy<=0)respawnPlayer('💥 OUT OF ENERGY!')}
function respawnPlayer(reason='💨 WATCH THE GAP!'){if(state.rescue>0){state.rescue--;player.position.copy(state.lastSafe);player.position.y=1.1;velY=4;say('🦁 RARY RESCUE!<br><small>MAX AURA SAVED YOU.</small>',1.5);return}state.energy=Math.max(3,state.energy);player.position.set(0,1.1,8);velY=0;say(reason+'<br><small>Back to the start of this level.</small>',1.4);updateHUD()}
function collectNumber(p){if(p.userData.collected)return;if(p.userData.index!==state.angka){say(`❌ NOT YET — FIND ${WORDS[state.angka][0]} (${state.angka})`,.85);tone(170,.12,'square',.05);return}p.userData.collected=true;p.visible=false;state.angka++;tone(520+state.angka*35,.12,'sine',.07);burst(p.position,0xffdf4b,20);if(state.angka===11){keyObj.visible=true;say('🔑 SEMUA ANGKA!<br><small>THE KEY HAS APPEARED.</small>',1.5)}updateHUD()}
function collectKey(){if(!keyObj.visible||state.hasKey)return;state.hasKey=true;keyObj.visible=false;tone(880,.18,'triangle',.08);tone(1320,.25,'sine',.05);burst(keyObj.position,0xffd53a,30);say('🔑 KUNCI FOUND!<br><small>HEAD TO THE SPORTS SHED.</small>',1.5);updateHUD()}
function spawnPower(type,pos){const g=new THREE.Group();let c=0xffe35a,symbol='★';if(type==='RESP'){c=0x59c6ff;symbol='◆'}if(type==='RESPECT'){c=0xff78bf;symbol='🤝'}if(type==='RARY'){c=0xffc72d;symbol='🦁'}const orb=sphere(.72,c,12);orb.material.emissive=new THREE.Color(c).multiplyScalar(.18);g.add(orb);const s=textSprite(symbol,'#fff','rgba(0,0,0,.62)',2.2);s.position.y=1.35;g.add(s);g.position.copy(pos);g.position.y=1.2;g.userData={type,phase:Math.random()*6,collected:false};world.add(g);powerups.push(g)}
function collectPower(p){if(p.userData.collected)return;p.userData.collected=true;p.visible=false;burst(p.position,0xffffff,28);const t=p.userData.type;if(t==='RESP'){state.respUntil=Math.max(state.respUntil,gameTime+16);say('◆ RESPONSIBILITY!<br><small>5 RAPID RICOCHETING DODGEBALLS.</small>',1.4)}else if(t==='RESPECT'){state.respectUntil=Math.max(state.respectUntil,gameTime+10);say('🤝 RESPECT!<br><small>FRUIT → CONFETTI. MR LEES → DANCE PARTY.</small>',1.6);for(const f of fruit){burst(f.position,0xff77bb,14);f.userData.dead=true;f.visible=false}}else if(t==='ACH'){state.achieverUntil=Math.max(state.achieverUntil,gameTime+14);state.invulnUntil=state.achieverUntil;say('★ ACHIEVER!<br><small>INVINCIBLE · FAST · AURA SMASH.</small>',1.5)}else{state.raryUntil=Math.max(state.raryUntil,gameTime+18);state.respUntil=Math.max(state.respUntil,gameTime+18);state.respectUntil=Math.max(state.respectUntil,gameTime+18);state.achieverUntil=Math.max(state.achieverUntil,gameTime+18);state.invulnUntil=state.raryUntil;state.energy=state.maxEnergy;state.rescue=1;say('🦁 RARY — MAX AURA!<br><small>FULL ENERGY · ALL PBS POWERS · EXTRA SPEED · 1 RESCUE.</small>',2)}updateHUD()}
function burst(pos,color=0xffffff,n=18){for(let i=0;i<n;i++){const m=sphere(.06+Math.random()*.07,color,6);m.position.copy(pos);world.add(m);particles.push({m,v:new THREE.Vector3((Math.random()-.5)*7,Math.random()*7,(Math.random()-.5)*7),life:1+Math.random()*.7})}}
function throwBall(angleOffset=0,speed=29){const b=sphere(.38,0xff5ca8,12);b.material.emissive=new THREE.Color(0x661638);b.position.copy(player.position);b.position.y+=2.4;const yaw=playerYaw+angleOffset;const dir=new THREE.Vector3(Math.sin(yaw),.05,Math.cos(yaw));b.userData={v:dir.multiplyScalar(speed).add(new THREE.Vector3(0,2.3,0)),life:5,bounces:0,dead:false};world.add(b);balls.push(b)}
function shoot(){if(throwCool>gameTime)return;throwCool=gameTime+.24;tone(300,.06,'triangle',.04);if(gameTime<state.respUntil||gameTime<state.raryUntil){for(const a of [-.18,-.09,0,.09,.18])throwBall(a,30)}else throwBall(0,29)}
function enemyFruit(e){if(e.userData.dead||gameTime<state.respectUntil)return;const f=sphere(.34,[0xff623e,0xf7d64a,0x82c84a][Math.floor(Math.random()*3)],10);f.position.copy(e.position);f.position.y+=2.5*(e.userData.scale||1);const dir=player.position.clone().sub(e.position);dir.y=0;dir.normalize();f.userData={v:dir.multiplyScalar(13).add(new THREE.Vector3(0,7.5,0)),life:5,dead:false};world.add(f);fruit.push(f)}
function killEnemy(e){if(e.userData.dead)return;e.userData.hp--;burst(e.position,0xff6ea9,10);if(e.userData.hp<=0){e.userData.dead=true;e.visible=false;tone(620,.12,'square',.05);if(Math.random()<.18)spawnPower(['RESP','RESPECT','ACH','RARY'][Math.floor(Math.random()*4)],e.position);if(e===boss)bossDefeated()}else if(e===boss)updateBossBar()}
function updateBossBar(){if(!boss)return;ui.bossName.textContent=`💪 ${boss.userData.name} · ${boss.userData.hp} HP`;ui.bossBar.style.width=`${Math.max(0,boss.userData.hp/boss.userData.maxHp*100)}%`}
function startBosses(){enemies.forEach(e=>{e.userData.dead=true;e.visible=false});if(level===5)bossQueue=[['Medium Mr Lee',50,1.65]];else bossQueue=[['Small Mr Lee',10,1.08],['Medium Mr Lee',50,1.6],['Large Mr Lee',100,2.15],['MEGA EVOLUTION MR LEE',200,3.0]];bossIndex=-1;spawnNextBoss()}
function spawnNextBoss(){bossIndex++;if(bossIndex>=bossQueue.length){boss=null;ui.bossWrap.style.display='none';say('🏆 MR LEE DEFEATED!<br><small>THE SPORTS SHED EXIT IS OPEN.</small>',2);return}const [name,hp,scale]=bossQueue[bossIndex];boss=makeBoss(name,hp,scale);boss.position.set(0,0,-175);boss.userData.homeX=0;boss.userData.homeZ=-175;boss.userData.phase=Math.random()*10;world.add(boss);enemies.push(boss);ui.bossWrap.style.display='block';updateBossBar();for(const [i,t] of ['RESP','RESPECT','ACH','RARY'].entries())spawnPower(t,new THREE.Vector3(-9+i*6,1,-158));say(`💪 ${name.toUpperCase()}!<br><small>${hp} HP · POWER-UPS INCOMING!</small>`,1.7)}
function bossDefeated(){tone(210,.22,'sawtooth',.08);tone(420,.3,'square',.05);spawnNextBoss()}
function updateMovement(dt){const turn=2.5*dt*(keys.run?1.1:1);if(keys.left)playerYaw+=turn;if(keys.right)playerYaw-=turn;player.rotation.y=playerYaw;let move=(keys.forward?1:0)-(keys.back?1:0);let speed=(keys.run?12:7.1);if(gameTime<state.achieverUntil)speed*=1.45;if(gameTime<state.raryUntil)speed*=1.65;if(move){player.position.x+=Math.sin(playerYaw)*speed*move*dt;player.position.z+=Math.cos(playerYaw)*speed*move*dt}player.position.x=THREE.MathUtils.clamp(player.position.x,-CORRIDOR/2+1,CORRIDOR/2-1);if(keys.jump&&onGround){velY=9.6;onGround=false;tone(260,.07,'square',.035)}velY-=22*dt;player.position.y+=velY*dt;const hole=inHole(player.position);if(!hole&&player.position.y<=1.1){player.position.y=1.1;velY=0;onGround=true;state.lastSafe.copy(player.position)}else if(hole)onGround=false;if(player.position.y<-8)respawnPlayer();if(keys.throw)shoot();keys.jump=false}
function updateCamera(dt){const dist=8.2,height=5.3;const desired=new THREE.Vector3(player.position.x-Math.sin(playerYaw)*dist,player.position.y+height,player.position.z-Math.cos(playerYaw)*dist);camera.position.lerp(desired,1-Math.pow(.002,dt));const look=player.position.clone().add(new THREE.Vector3(Math.sin(playerYaw)*3,2.2,Math.cos(playerYaw)*3));camera.lookAt(look)}
function updatePickups(dt){for(const p of pickups){if(p.userData.collected)continue;p.rotation.y+=dt*1.3;p.position.y=p.userData.baseY+Math.sin(gameTime*2+p.userData.phase)*.23;if(collisionXZ(player,p,1.6)&&Math.abs(player.position.y-p.position.y)<2)collectNumber(p)}if(keyObj&&keyObj.visible){keyObj.rotation.y+=dt*1.5;keyObj.position.y=2+Math.sin(gameTime*2.5)*.25;if(collisionXZ(player,keyObj,2))collectKey()}for(const p of powerups){if(p.userData.collected)continue;p.rotation.y+=dt;p.position.y=1.2+Math.sin(gameTime*3+p.userData.phase)*.3;if(collisionXZ(player,p,1.8))collectPower(p)}}
function updateEnemies(dt){enemyThrowClock-=dt;for(const e of enemies){if(e.userData.dead)continue;const sc=e.userData.scale||1;if(gameTime<state.respectUntil){e.rotation.y=Math.sin(gameTime*6+e.userData.danceSeed)*1.3;e.position.y=Math.abs(Math.sin(gameTime*7+e.userData.danceSeed))*.45;continue}else e.position.y=0;const dz=player.position.z-e.position.z,dx=player.position.x-e.position.x,dist=Math.hypot(dx,dz);if(dist<45){const chase=e===boss?2.2:1.25;if(dist>3){e.position.x+=dx/dist*chase*dt;e.position.z+=dz/dist*chase*dt}e.rotation.y=Math.atan2(dx,dz);if(enemyThrowClock<=0&&dist<32){enemyFruit(e);enemyThrowClock=e===boss?.75:1.7+Math.random()*1.2}}else{e.position.x=e.userData.homeX+Math.sin(gameTime*.7+e.userData.phase)*4;e.rotation.y=Math.sin(gameTime*.4+e.userData.phase)}if(gameTime<state.achieverUntil&&dist<2.8*sc){killEnemy(e)}else if(dist<1.3+sc*.6){if(player.position.y>2.2*sc&&velY<0){killEnemy(e);velY=7.2;tone(470,.09,'square',.05)}else damagePlayer(1,new THREE.Vector3(dx?Math.sign(dx)*1.2:0,0,dz?Math.sign(dz)*1.2:0))}}}
function updateBalls(dt){for(const b of balls){if(b.userData.dead)continue;const v=b.userData.v;v.y-=16*dt;b.position.addScaledVector(v,dt);b.userData.life-=dt;if(b.position.y<.4&&!inHole(b.position)){b.position.y=.4;v.y=Math.abs(v.y)*.7;b.userData.bounces++;tone(180+Math.min(250,b.userData.bounces*35),.025,'sine',.015)}if(Math.abs(b.position.x)>CORRIDOR/2-.4){b.position.x=THREE.MathUtils.clamp(b.position.x,-CORRIDOR/2+.4,CORRIDOR/2-.4);v.x*=-.86;b.userData.bounces++}for(const e of enemies){if(!e.userData.dead&&b.position.distanceTo(e.position.clone().add(new THREE.Vector3(0,1.7*(e.userData.scale||1),0)))<1.1*(e.userData.scale||1)){killEnemy(e);v.x*=-.65;v.z*=-.65;v.y=Math.abs(v.y)+2.5;b.userData.bounces++;break}}if(b.userData.life<=0||b.position.y<-8){b.userData.dead=true;b.visible=false}}}
function updateFruit(dt){for(const f of fruit){if(f.userData.dead)continue;const v=f.userData.v;v.y-=17*dt;f.position.addScaledVector(v,dt);f.rotation.x+=dt*5;f.userData.life-=dt;if(gameTime<state.respectUntil){burst(f.position,0xff77aa,10);f.userData.dead=true;f.visible=false;continue}if(f.position.distanceTo(player.position.clone().add(new THREE.Vector3(0,1.8,0)))<1.1){damagePlayer(1);f.userData.dead=true;f.visible=false}if(f.position.y<.25&&!inHole(f.position)){f.position.y=.25;v.y=Math.abs(v.y)*.35;v.x*=.8;v.z*=.8}if(f.userData.life<=0||f.position.y<-8){f.userData.dead=true;f.visible=false}}}
function updateParticles(dt){for(const p of particles){p.life-=dt;p.v.y-=11*dt;p.m.position.addScaledVector(p.v,dt);p.m.scale.multiplyScalar(.985);if(p.life<=0)p.m.visible=false}particles=particles.filter(p=>p.life>0)}
function maybeBossTrigger(){if((level===5||level===10)&&state.hasKey&&!boss&&bossQueue.length===0&&player.position.z<-165)startBosses()}
function exitReady(){if(!state.hasKey)return false;if(level===5||level===10)return bossQueue.length>0&&bossIndex>=bossQueue.length;return true}
function checkExit(){maybeBossTrigger();if(player.position.z<-208&&exitReady()){if(level<10){level++;buildLevel()}else{running=false;ui.overlay.style.display='grid';$('#card').innerHTML=`<div class="kicker">MISI SELESAI</div><div class="title">YOU FOUND<br>THE KEYS!</div><p class="story">All ten levels cleared. Mr Lee has survived Sports Class, Running Club, netball, basketball, carnivals, athletics, Indonesian Week and his own <b>MEGA EVOLUTION</b>.</p><button id="again" style="border:0;border-radius:16px;padding:15px 26px;background:#f8d849;color:#112217;font-size:20px;font-weight:1000">PLAY AGAIN</button>`;$('#again').onclick=()=>location.reload()}}else if(player.position.z<-207&&!state.hasKey){say('🔒 SPORTS SHED LOCKED — FIND THE KEY!',.8)}else if(player.position.z<-207&&(level===5||level===10)&&!exitReady()){say('💪 DEFEAT MR LEE FIRST!',.8)}}
function updateAura(){const active=gameTime<state.achieverUntil||gameTime<state.raryUntil;player.userData.aura.material.opacity=active?.72:0;player.userData.aura.rotation.z+=.06;player.userData.aura.scale.setScalar(1+Math.sin(gameTime*5)*.08)}
function animate(){requestAnimationFrame(animate);const now=performance.now();let dt=Math.min(.033,(now-last)/1000);last=now;if(running){gameTime+=dt;updateMovement(dt);updatePickups(dt);updateEnemies(dt);updateBalls(dt);updateFruit(dt);updateParticles(dt);updateAura();checkExit();if(messageTimer&&gameTime>messageTimer){ui.msg.classList.remove('show');messageTimer=0}updateHUD()}updateCamera(dt);renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
addEventListener('keydown',e=>{if(e.code==='KeyW'||e.code==='ArrowUp')keys.forward=true;if(e.code==='KeyS'||e.code==='ArrowDown')keys.back=true;if(e.code==='KeyA'||e.code==='ArrowLeft')keys.left=true;if(e.code==='KeyD'||e.code==='ArrowRight')keys.right=true;if(e.code==='ShiftLeft'||e.code==='ShiftRight')keys.run=true;if(e.code==='KeyJ')keys.jump=true;if(e.code==='Space'){keys.throw=true;e.preventDefault()}});
addEventListener('keyup',e=>{if(e.code==='KeyW'||e.code==='ArrowUp')keys.forward=false;if(e.code==='KeyS'||e.code==='ArrowDown')keys.back=false;if(e.code==='KeyA'||e.code==='ArrowLeft')keys.left=false;if(e.code==='KeyD'||e.code==='ArrowRight')keys.right=false;if(e.code==='ShiftLeft'||e.code==='ShiftRight')keys.run=false;if(e.code==='Space')keys.throw=false});
for(const b of document.querySelectorAll('.tbtn')){const k=b.dataset.k;const down=e=>{e.preventDefault();b.classList.add('on');if(k==='jump')keys.jump=true;else keys[k]=true};const up=e=>{e.preventDefault();b.classList.remove('on');if(k!=='jump')keys[k]=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)}
ui.start.addEventListener('click',()=>{try{audio()}catch{}ui.overlay.style.display='none';running=true;buildLevel()});
buildLevel();running=false;animate();
